#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-dependency-plugin
Version  : 3.1.1
Release  : 1
URL      : https://github.com/apache/maven-dependency-plugin/archive/maven-dependency-plugin-3.1.1.tar.gz
Source0  : https://github.com/apache/maven-dependency-plugin/archive/maven-dependency-plugin-3.1.1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/3.1.1/maven-dependency-plugin-3.1.1.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/3.1.1/maven-dependency-plugin-3.1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
<!---
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

%prep

%build

%install

%files
%defattr(-,root,root,-)
